language: node_js
node_js:
- '5'
notifications:
  email: false
  slack:
    rooms:
      secure: ZpnM4rlh0JdWijrLWl9Ir08y+m0wn89n3qk8t34MQqeg+vDQu79YD5eaYuqF/01gSgrcrvWMAFqwGrCerngkAzHJtIdQCMkXiB5AmuSZjjkICmpBXy/t5AmehlRslLlH58dVpmU3TTY4pD7NQ3tIJ0lLOWv9j9Qq1xggOMUPc4tRy+b5cDWNyeSAGKv8BdRwPiP+6Ziwwn31an8q9lLz9Rk+iEWXQKjKBnfhnYMlm38aUgSsZGKvxCsFEVEIW5nJbELwSzbPtDtCmG2YLHnl9n4m2RcYwNOssZi5gPdGe4mK6hbsl+CGTyxHoZX8BcQaiuzNQRWjkQQvRfUQkpKLkZ57bg5RZO1OX/X5Y5SY65xiHoZDIIxj1Py4WfWpVygHP2yUEzoIVZAxvGXLH0cii9LDntNpejpU+90RMH1DJd7sZJJnRGogHwpLKMG4aDpGbIEoCv/32ykvAhiRD6mTPe5GAv4wAcGMRc/3tmpvHKNnNvYa+GqEPei4A34ysEPp32KOz3ntVk0+MnWaol0uGiJ7aeEfnJnfctd6MkxJSdssuk0tu5jUYNLrkbiKPUeGXwrxzY0lkZkoJCmFjGDe+UQFBHpaZyubocOrZUQV8tOdGbwN/J/UrB/tQDEBSBLUaZHwzfKqG4vzL6i6uU5Ao4xvCbhX3xkPXiXFtbD+QLg=
after_success:
- sh ./scripts/publish-docs.sh
