language: node_js
node_js:
- '5'
notifications:
  email: false
  slack:
    secure: HAEj3qoHDFk1In+Vc4km8mKbwhQMkKaF/m9rMyVFz/zNvJnSFRjkHm1dh28ZjPA+X1Dm2YCIFbVR9yBvmuG3fGgHo2WPdtRiG2nWTeqQReyOLzCgR4zuLCQQU75UOZ47lhpx3a5t2BpjEWdqTDBlE2tywv+jIbpqrY/TIxLDw1YJpOTeMq+2kZaN4czCziuJPCr0BGL+5J1nQ2anaDmqBem+6lZ3UelFvJL0+WSSRDBuypF65t0XooRtfJPTR2LOouxJSmPVBJw/frVzFQ5EezhyrTkicdcLzzBU6gD7DvndSLVLjBnvH27n1rmhwhYSzV6OxgBQicfVurh/Oa+v/khC4YRizwU3af+dQnOvANKjlZhOFxWJD5rNNa0o79s8475mR/Z6XwL8ZkOKTPyaL1/sgZY6PbiSMpTdS+y0bPzxrsvLBDfx2njIx6jS8Z1uQm01dJsaBRhNAYM/3ttYWI8gBdQQb8Jh5QwmhiuXtcuoi1/nVmRLelkVEo1v2a2yk4K+FGpTuOoNNGp5uBc0S/ELlH/B7E4WXJigCFyZVnYpBRAknqCQtrdwcGoXgLBOj6RB7WP+ty97wz8d4RpgA9hbD7vc7CTOOvyvMKjbZ1K6KmmLifNSHnKRPgtDznp1/YeFj33D0cyyYkCBkqNVFt897g4zS9QMPGP3fnW6ztc=
after_success:
- sh ./scripts/publish-docs.sh
