language: node_js
node_js:
- '5'
notifications:
  email: false
  slack:
    room:
      secure: yCPMrmJvSzkwgcLPhBLIGELi0R5lzqpWX2W/9RVdkgyMbpz7Lb8eU0V94VeIa/0sSFi0HTTFUEZnYBqReLULSUwuY8HnCiZmcxo8SNrlk11nB/FWfE6sPlJzioXMQdDLUySSoE2k9FFZ4G5E6mdOJwgaqHkBCBZf9GKyKzIIjvSqzegmxEpRwiMSeXK/7t9Z7z8mlYhWcDmlyqusuVzCO17fWnDrhEUQCYgxxA/T4W++4yvHpQY4t119J4KLHS4gvzfclkpzuDdKzIetZfyU5dFL5S5D8y5+by6/McVLmeV4QZLL7pT13czw3fNyd3QKHaSr5mOMls8KQyS//uGs9XaHvT0fcPdlMoxlAQxADZrdj9tupY4Wrnx9YYYnJlsTHVM/j1nOKed9jNLe8nLiluybrbR2VTNMiJVEeNNidrVWBEFyZK+4qIknRMLgja44DxdbAmn5qcZEvoLgYZwZjE3eZrBU+nILyQeVa0E/a9caJogv61Qyvv7FgNqnQNmaosnOg0n/hThkdEGop3kV8aibdpeiNYpQJXHTr4YQ/xb6IjI3KhrZn0dVhAVwQ8QG7J1RykxZMZ017ja9KgINphp6BLyUwTrY6sGXkdgY5hXeLnS9dnq/CG7bTEnNWWJA/ET0tiQwjF+WLto0AxFaV7XhP2/IMNw3xq6QHt1cVp8=
after_success:
- sh ./scripts/publish-docs.sh
